version: '3.8'
services:
  go_crawler:
    build:
      context: ./backend/go-crawler
      dockerfile: Dockerfile
    container_name: go_crawler
    ports:
      - "8080:8080"

  ai_model:
    build:
      context: ./backend/ai-model
      dockerfile: Dockerfile
    container_name: ai_model
    ports:
      - "5000:5000"

  node_client:
    build:
      context: ./frontend/puppeteer-test
      dockerfile: Dockerfile
    container_name: node_client
    ports:
      - "3000:3000"
