name: vuln_scanner_dashboard
description: A FlutterFlow-based dashboard for the vulnerability scanner.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  json_annotation: ^4.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0  # Updated to latest compatible version
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

